version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - '@ethanneff'
    labels:
      - ':robot: dependabot'
      - ':sunglasses: needs review'
    commit-message:
      prefix: 'chore:'
