language: node_js
node_js: 10
cache: yarn
notifications:
  email: false
install: yarn install
jobs:
  include:
    - stage: validate
      name: valitate
      script: yarn lint
      script: yarn test
      script: CI=false yarn build
    - stage: release
      name: release
      script: codecov
      script: npm run travis-deploy-once "npm run semantic-release"
    - stage: deploy
      name: deploy
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        keep-history: true
        github-token: "$GH_TOKEN"
        on:
          branch: master