language: node_js
node_js: 10
cache: yarn
notifications:
  email: false
install: yarn install
jobs:
  include:
    - stage: validate
      name: lint
      script: yarn lint
    - name: test
      script: yarn test && codecov
    - stage: release
      name: npm
      script: npm run travis-deploy-once "npm run semantic-release"
    - name: pages
      script: CI=false yarn build
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        keep-history: true
        github-token: "$GH_TOKEN"
        on:
          branch: master
