matrix:
  include:
    - language: node_js
      node_js: 14
      cache: yarn
      notifications:
        email: false
      install:
        - yarn install
      script:
        - yarn lint
        - yarn test
        - CI=false yarn build
      after_success:
        - codecov
        - npm run travis-deploy-once "npm run semantic-release"
      branches:
        except:
          - "/^v\\d+\\.\\d+\\.\\d+$/"
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        keep-history: true
        github-token: '$GH_TOKEN'
        on:
          branch: master

    - language: objective-c
      osx_image: xcode8.3
      install:
        - bundle install
      script:
        - fastlane ios core

    - language: objective-c
      osx_image: xcode8.3
      install:
        - bundle install
      script:
        - fastlane android core
